spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lab_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: cjw666666*

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0

spring:
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

jwt:
  secret: demo-jwt-secret-key-for-spring-security-2026
  expiration: 7200000
